exclude: [Archive]
defaults:
    -
        scope:
            path: "" # all files on the site
        values:
            layout: "default"
    -
        scope:
            path: "docs"
        values:
            layout: "transcript"
readme_index:
    enabled: true
kramdown:
    parse_block_html: true