exclude: [Archive]
markdown: GFM
defaults:
  -
    scope:
      path: "" # all files on the site
    values:
      layout: "default"
  -
    scope:
      path: "docs"
    values:
      layout: "transcript"
      todd_factcheck: "Todd in the Shadows. <em>I Fact-Checked The Worst Video Essayist On YouTube</em> [Video]. YouTube. https://www.youtube.com/watch?v=A6_LW1PkmnY"
      hbomb_factcheck: "Hbomberguy. <em>Plagiarism and You(Tube)</em> [Video]. YouTube. https://www.youtube.com/watch?v=yDp3cB5fHXQ"
readme_index:
  enabled: true
collections:
  videos:
    output: true
    permalink: /:collection/:name
    layout: transcript
    yt:
      todd_factcheck: "Todd in the Shadows. <em>I Fact-Checked The Worst Video Essayist On YouTube</em> [Video]. YouTube. https://www.youtube.com/watch?v=A6_LW1PkmnY"
      hbomb_factcheck: "Hbomberguy. <em>Plagiarism and You(Tube)</em> [Video]. YouTube. https://www.youtube.com/watch?v=yDp3cB5fHXQ"
